// App actions
export const CURRENT_USER = 'CURRENT_USER';
export const LOAD_ASSETS = 'LOAD_ASSETS';

// Host actions
export const LISTEN_HOST_EVENTS = 'LISTEN_HOST_EVENTS';
export const UNLISTEN_HOST_EVENTS = 'UNLISTEN_HOST_EVENTS';
export const LISTEN_HOST_EVENT = 'LISTEN_HOST_EVENT';
export const UNLISTEN_HOST_EVENT = 'UNLISTEN_HOST_EVENT';
export const LISTEN_MY_VIEWERS = 'LISTEN_MY_VIEWERS';
export const UNLISTEN_MY_VIEWERS = 'UNLISTEN_MY_VIEWERS';

// Audience actions
export const LISTEN_GUEST_EVENT = 'LISTEN_GUEST_EVENT';
export const UNLISTEN_GUEST_EVENT = 'UNLISTEN_GUEST_EVENT';
export const LISTEN_TICKET = 'LISTEN_TICKET';
export const LISTEN_VIEWERS = 'LISTEN_VIEWERS';
