export default {
  APPLICATION_NAME: 'Kaloo',
  APP_FONT: 'System',
  AGORA_APP_ID: '90aa9f5746e946a9b848196b2bf36b7e',
  EVENT_TYPE: {
    CALL: 'CALL',
    BROADCAST: 'BROADCAST'
  },
  EVENT_STATUS: {
    SCHEDULED: 'SCHEDULED',
    IN_PROGRESS: 'IN_PROGRESS',
    SUSPENDED: 'SUSPENDED',
    COMPLETED: 'COMPLETED'
  },
  TicketStatus: {
    RESERVED: 'RESERVED',
    SOLD: 'SOLD',
    IN_USE: 'IN_USE'
  },
  HOST_UID: 1000001,

}