export default {
  APPLICATION_NAME: 'Kaloo',
  APP_FONT: 'System',
  AGORA_APP_ID: 'a0ee6b5742ca4cfe84d1e9fa4c97b946',
  EVENT_TYPE: {
    MEETING: 'MEETING',
    BROADCAST: 'BROADCAST'
  },
  EVENT_STATUS: {
    SCHEDULED: 'SCHEDULED',
    IN_PROGRESS: 'IN_PROGRESS',
    SUSPENDED: 'SUSPENDED',
    COMPLETED: 'COMPLETED'
  },
  TicketStatus: {
    RESERVED: 'RESERVED',
    SOLD: 'SOLD',
    IN_USE: 'IN_USE'
  }

}